version: '3' # Cela indique que nous utilisons la version 3 de la syntaxe Docker Compose

services:
  postgres:
    image: postgres:latest
    environment: # Définit les variables d'environnement pour configurer PostgreSQL.
      POSTGRES_USER: airflow 
      POSTGRES_PASSWORD: airflow 
      POSTGRES_DB: airflow
    ports:
      - "5432:5432" # Expose le port 5432 du conteneur PostgreSQL sur le port 5432 de l'hôte.
    networks:
      - etl_network
    volumes: # Monte un volume nommé postgres_data pour persister les données de PostgreSQL.
      - ./postgres_data/createdb.sql:/var/lib/postgresql/createdb.sql

  scraper:
    build:
      context: ./scraper
      dockerfile: Dockerfile
    command: ["python", "scraper.py"]
    networks:
      - etl_network
    depends_on:
      - postgres

  init-airflow:
    image: apache/airflow:latest
    depends_on:
      - postgres
    networks:
      - etl_network
    environment:
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
    command: >
      bash -c "
      airflow db init &&
      airflow users create --username admin --password admin --firstname Air --lastname Flow --role Admin --email admin@example.com
      "

  webserver:
    build: 
      context: .
      dockerfile: Dockerfile
    user: root
    depends_on:
      - postgres
    networks:
      - etl_network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./scraper:/opt/airflow/scraper
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      EXECUTOR: Local
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__WEBSERVER__DEFAULT__USER_USERNAME: airflow
      AIRFLOW__WEBSERVER__DEFAULT__USER_PASSWORD: airflow
      AIRFLOW__WWW__USER__USER_USERNAME: airflow
      AIRFLOW__WWW__USER__USER_PASSWORD: airflow
      AIRFLOW__WEBSERVER__SECRET_KEY: secret
    ports:
      - "8080:8080"
    command: webserver

  scheduler:
    build: 
      context: .
      dockerfile: Dockerfile
    user: root
    depends_on:
      - postgres
    networks:
      - etl_network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./scraper:/opt/airflow/scraper
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      EXECUTOR: Local
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgres+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__WEBSERVER__DEFAULT__USER_USERNAME: airflow
      AIRFLOW__WEBSERVER__DEFAULT__USER_PASSWORD: airflow
      AIRFLOW__WWW__USER__USER_USERNAME: airflow
      AIRFLOW__WWW__USER__USER_PASSWORD: airflow
      AIRFLOW__WEBSERVER__SECRET_KEY: secret
    command: scheduler

      
networks:
  etl_network:
    driver: bridge
