version: '3' # Cela indique que nous utilisons la version 3 de la syntaxe Docker Compose

services:
  postgres:
    image: postgres:latest
    environment: # Définit les variables d'environnement pour configurer PostgreSQL.
      POSTGRES_USER: airflow 
      POSTGRES_PASSWORD: airflow 
      POSTGRES_DB: airflow
    ports:
      - "5432:5432" # Expose le port 5432 du conteneur PostgreSQL sur le port 5432 de l'hôte.
    networks:
      - etl_network
    volumes: # Monte un volume nommé postgres_data pour persister les données de PostgreSQL.
      - ./postgres_data/createdb.sql:/var/lib/postgresql/createdb.sql

  scraper:
    build:
      context: ./scraper
      dockerfile: Dockerfile
    command: ["python", "scraper.py"]
    networks:
      - etl_network
    depends_on:
      - postgres
      
networks:
  etl_network:
    driver: bridge
